In [2]:
!pip install transformers

  Using cached transformers-4.53.2-py3-none-any.whl.metadata (40 kB)
  Using cached huggingface_hub-0.33.4-py3-none-any.whl.metadata (14 kB)
  Using cached tokenizers-0.21.2-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
  Using cached safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Using cached transformers-4.53.2-py3-none-any.whl (10.8 MB)
Using cached huggingface_hub-0.33.4-py3-none-any.whl (515 kB)
Using cached safetensors-0.5.3-cp38-abi3-win_amd64.whl (308 kB)
Using cached tokenizers-0.21.2-cp39-abi3-win_amd64.whl (2.5 MB)


In [4]:
from transformers import BertTokenizer,BertModel

In [5]:
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

c:\Users\Anirudh\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Anirudh\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
tokenizer("I love Apple", return_tensors='pt')##101 is cls and 102 is sep

{'input_ids': tensor([[ 101, 1045, 2293, 6207,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [8]:
tokens=tokenizer(["I love Apple", "I love Orange and Banana"], return_tensors='pt', padding=True)
tokens

{'input_ids': tensor([[  101,  1045,  2293,  6207,   102,     0,     0],
        [  101,  1045,  2293,  4589,  1998, 15212,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1]])}

In [10]:
tokens=tokenizer(["I love Apple", "I love Orange and Banana"], return_tensors='pt', padding="max_length", max_length=10)
tokens

{'input_ids': tensor([[  101,  1045,  2293,  6207,   102,     0,     0,     0,     0,     0],
        [  101,  1045,  2293,  4589,  1998, 15212,   102,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}

In [11]:
tokens=tokenizer(["I love Apple", "you are what you eat"], return_tensors='pt', padding="max_length", max_length=5, truncation=True)
tokens

{'input_ids': tensor([[ 101, 1045, 2293, 6207,  102],
        [ 101, 2017, 2024, 2054,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])}

In [12]:
tokens=tokenizer("I love Apple", return_tensors='pt')
tokens

{'input_ids': tensor([[ 101, 1045, 2293, 6207,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1]])}

In [13]:
model=BertModel.from_pretrained('bert-base-uncased')
outputs=model(**tokens)##outputs the contextualized embeddings

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [30]:
outputs[0][0].shape

torch.Size([5, 768])

In [14]:
outputs['last_hidden_state']

tensor([[[ 0.0348,  0.2395, -0.0695,  ..., -0.1550,  0.0836,  0.0415],
         [ 0.0349,  0.4142,  0.0838,  ..., -0.2773,  0.4387,  0.0628],
         [ 0.8293,  0.8872,  0.7468,  ..., -0.0368,  0.1503, -0.1132],
         [-0.4576, -0.0591, -0.6812,  ...,  0.8809,  0.1841, -0.6385],
         [ 0.7952,  0.2601, -0.1495,  ..., -0.3544, -0.5979, -0.4172]]],
       grad_fn=<NativeLayerNormBackward0>)

In [18]:
outputs['last_hidden_state'].shape##total of 5 vectors,each is a contextualized embedding for tokens in the sentence "i love apple" along with cls and sep tokens and each embedding has 768 dimensions

torch.Size([1, 5, 768])

In [19]:
outputs['last_hidden_state'][0,0,:]##cls token embedding

tensor([ 3.4830e-02,  2.3955e-01, -6.9502e-02, -9.7389e-02, -5.3633e-02,
        -1.1356e-01,  7.0408e-02,  4.1732e-01,  2.4496e-02, -9.9775e-02,
         1.2199e-02, -9.6466e-02,  7.2036e-02,  2.9988e-01,  5.5077e-02,
        -9.9361e-02, -4.4768e-02,  3.0743e-01,  2.5978e-01, -1.2315e-01,
         1.1982e-02, -1.3827e-01, -2.6614e-01, -1.2329e-01,  6.8267e-02,
        -9.3985e-02, -5.7705e-02, -1.1863e-01,  2.3585e-01,  1.2366e-01,
         1.7388e-01,  7.4968e-02,  1.5297e-01,  1.5496e-01, -3.3823e-03,
         4.0207e-03,  1.4507e-01, -5.6994e-02, -1.6095e-01,  3.3302e-02,
         7.7899e-02, -5.1480e-02,  1.9162e-01, -6.9063e-02,  2.1740e-02,
        -1.5912e-01, -1.5442e+00, -3.7362e-02, -1.5152e-01, -1.7900e-01,
         2.3778e-01,  6.8626e-02,  1.8514e-01,  1.6067e-01,  2.1592e-03,
         1.2569e-01, -1.1361e-01,  6.4751e-01,  1.1786e-01,  2.3940e-01,
         1.0387e-01, -1.8212e-02, -7.6512e-02,  1.4786e-01, -8.0633e-02,
         1.0567e-01,  1.6864e-02,  1.8352e-01, -8.5

In [20]:
outputs['last_hidden_state'][0,1,:]##i token contextualized embedding

tensor([ 3.4922e-02,  4.1424e-01,  8.3803e-02, -3.4062e-01,  1.3014e-03,
         2.8504e-01, -4.2294e-01,  1.2705e+00, -2.2102e-01, -3.2335e-01,
        -1.9773e-01, -5.2005e-01,  3.6977e-01,  4.8968e-01,  1.7865e-01,
         1.6030e-01,  4.8044e-01,  1.7797e-01,  4.8466e-01,  5.4206e-01,
         1.9840e-01, -9.1789e-02, -9.7713e-01,  2.1757e-01,  4.0002e-01,
         3.5853e-01, -4.8199e-01, -1.0845e-01,  2.2147e-01, -2.0643e-01,
        -1.3587e-02, -2.2858e-01,  4.1361e-01,  2.7478e-01, -6.2764e-01,
        -7.0622e-02,  1.8081e-01, -3.5946e-01, -6.1078e-01, -9.3527e-02,
        -1.6518e-03, -4.2114e-01,  7.8211e-02, -7.0488e-01, -5.7267e-02,
        -2.8517e-01,  2.1300e-01, -1.8760e-01,  3.7809e-01, -8.5746e-01,
         4.2555e-02, -9.3565e-02,  7.4110e-02,  2.1248e-01, -2.4103e-01,
         1.2041e+00, -2.6262e-02, -3.7280e-01, -1.1963e-02,  4.4922e-01,
        -6.6265e-02,  6.6236e-02,  5.8858e-01, -3.9099e-01, -5.4515e-01,
         4.8712e-01, -2.5137e-01, -1.4593e-01,  1.1

In [21]:
outputs['pooler_output']##is single vector representation of the sentence "I love Apple" obtained by applying a linear transformation and tanh activation on the cls token embedding
outputs['pooler_output'].shape##single vector of 768 dimensions

torch.Size([1, 768])

In [23]:
outputs['pooler_output'][0,:]##single vector representation of the sentence "I love Apple"

tensor([-7.9986e-01, -1.9204e-01,  5.6327e-01,  5.4469e-01, -3.3741e-01,
        -1.1991e-01,  8.2360e-01,  1.8826e-01,  2.3934e-01, -9.9930e-01,
         2.3771e-01, -6.2918e-02,  9.5989e-01, -2.2699e-01,  8.9831e-01,
        -4.0625e-01,  4.8323e-02, -5.0426e-01,  3.6781e-01, -6.9311e-01,
         4.8824e-01,  5.8209e-01,  5.7051e-01,  2.0574e-01,  3.4963e-01,
         5.0834e-02, -4.3369e-01,  8.7834e-01,  9.1272e-01,  6.2646e-01,
        -5.6520e-01,  1.3202e-01, -9.6318e-01, -1.7863e-01,  5.2006e-01,
        -9.6060e-01,  1.4361e-01, -7.1320e-01, -1.5553e-02,  3.8151e-02,
        -8.2203e-01,  2.0462e-01,  9.8501e-01, -1.1017e-01, -1.6533e-01,
        -2.9638e-01, -9.9879e-01,  2.1140e-01, -7.7902e-01, -4.0847e-01,
        -3.5355e-01, -5.9057e-01,  1.1364e-01,  3.3172e-01,  3.0520e-01,
         4.0868e-01, -1.1499e-01,  1.2203e-01, -8.7280e-02, -4.6611e-01,
        -5.6292e-01,  1.7452e-01,  1.7835e-01, -8.1298e-01, -4.0044e-01,
        -5.6546e-01, -7.0548e-02, -1.5118e-01, -2.0

In [26]:
##CLS IS ALSO EMBEDDING FOR THE WHOLE SENTENCE
###POOLER OUTPUT IS ALSO EMBEDDING FOR THE WHOLE SENTENCE,WHICH IS OBTAINED BY PASSING CLS TOKEN THROUGH A NEURAL NETWORK AND TAKING TANH OF IT which is activation function

In [25]:
tokenizer.convert_ids_to_tokens(tokens['input_ids'][0])##converts token ids to tokens

['[CLS]', 'i', 'love', 'apple', '[SEP]']